#ifndef MESH_FLAT_HPP
#define MESH_FLAT_HPP

#include "../maths/vertex.hpp"
#include "../maths/color.hpp"
#include "../types.h"
#include "../bitwise.h"
#include "mesh_base.hpp"
#include <string>

namespace kk3d {
namespace mesh {

/**
 * The basic camera object in KK3D.
 * This object contains 3D transformation and a view matrix for cameras.
 */
class MeshFlat : public MeshBase {
public:
    /**
     * The vertex class used by the model mesh. This contains the data sent to the shader for static models.
     */
    class Vertex {
    public:
        math::Vertex3D _v;                  /**< Vertex */
        math::Color4F _c;                   /**< Color */
        math::Vertex2D _uv;                 /**< Texture UV */
    };

    static const int OFFSET_VERTEX = 0;
    static const int OFFSET_COLOR = OFFSET_VERTEX + sizeof(math::Vertex3D);
    static const int OFFSET_UV = OFFSET_COLOR + sizeof(math::Color4F);
    static const GLsizei OFFSET_STRIDE = OFFSET_UV + sizeof(math::Vertex2D);

protected:
    Vertex *_vert;                          /**< Vertex data of the mesh. */
    GLsizei _size,                          /**< Number of vertexes. */
            _count;                         /**< Number of indexes. */
    GLushort *_index;                       /**< Index list. */
    GLuint _buff;                           /**< Buffer object ID. */
    int _flags;                             /**< Internal flags. */

public:

    /**
     * Basic constructor.
     * No values are set, this creates a blank GL object.
     */
    MeshFlat();
    /**
     * Basic constructor setting some values.
     * The constructor sets only the ID of the mesh.
     * @param i The ID of the object.
     */
    MeshFlat(int i);
    /**
     * Basic constructor setting some values.
     * The constructor sets only the name.
     * @param n The name of the object.
     */
    MeshFlat(std::string n);
    /**
     * Basic destructor.
     * Clears the data generated by the object.
     */
    ~MeshFlat();

    void prepareVertex(int c);
    void prepareIndex(int c);
    Vertex * getVertexes();
    GLushort * getIndexes();
    GLsizei getCount();
    GLsizei getSize();
    GLuint getBufferID();
    void createBuffer();
    int getFlags();
    void clearData();
};

};
};

#endif



